### ISSUE TITLE
Test project contains invalid references to new widget

### ISSUE THREAD

**Issue by twiggler** [mendix/generator-mendix#14]
When creating a new widget with default parameters using 'yo mendix', the resulting test project contains invalid references to the newly created widget. 
Error message in the modeler: 

> Could not find widget type WidgetName.widget.WidgetName

**Comment by JelteMX** [comment]
This is a known problem with the [AppStoreWidgetBoilerplate](https://github.com/mendix/AppStoreWidgetBoilerplate/issues/36) and we are going to release a new test-project in Q3. Closing this issue here
