### ISSUE TITLE
Javascript error when running the generated test project

### ISSUE THREAD

**Issue by twiggler** [mendix/generator-mendix#15]
I get a JS error in the minified version of the DOJO library when running the test project:
![image](https://cloud.githubusercontent.com/assets/12800443/15566303/66d0bb82-2320-11e6-960e-9a6d7b426bf2.png)

**Comment by JelteMX** [comment]
This has nothing to do with the generator, it's an [issue with the test-project](https://github.com/mendix/AppStoreWidgetBoilerplate/issues/36). We are going to work on that later on. This Javascript error is not due to the generated widget
