### ISSUE TITLE
Running yo mendix throws error

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/generator-mendix#17]
For some reason the generator raises an error after running yo mendix, unable to scaffold a new widget

See screenshot for stacktrace. I tried updating the generator using 'yo' but that didn't change anything

![image](https://cloud.githubusercontent.com/assets/2244753/15700003/7941cde6-27d1-11e6-8c4f-097f7f3a131b.png)

**Comment by Mcpoowl** [comment]
Spoke too soon. Updating yo  (using npm update -g) aswell as the mendix generator fixes the problem. Notices there was a new yeoman version available

**Comment by JelteMX** [comment]
Yeah that's correct. I also mentioned that in the [prerequisites](https://github.com/mendix/generator-mendix#prerequisites-you-only-have-to-do-this-once). Yeoman underwent a big chunk of refactoring, that's why the generator breaks on older versions

**Comment by Mcpoowl** [comment]
Ah, I didnt read the readme since it always worked in the past. Thanks for
letting me know!
Op 1 jun. 2016 10:28 a.m. schreef "Jelte Lagendijk" <
notifications@github.com>:
