### ISSUE TITLE
Changes in Template and CSS are not copied to deployment

### ISSUE THREAD

**Issue by remcos** [mendix/generator-mendix#23]
When updating the HTML Template or CSS sheets of a widget, I have to restart the application to see the effects. Would be really nice if it would directly copy the changes to the deployment directory.

**Comment by JelteMX** [comment]
See README: 
> It will also copy any changed Javascript files to your deployment folder. This means you do not have to redeploy locally, you can just refresh your browser. For changes in XML or CSS you will still need to synchronize your project directory (press F4 in the modeler) and redeploy.

For CSS that is correct. For HTML Templates, it should work. I'll investigate that.
