### ISSUE TITLE
By default the test project theme folder is excluded

### ISSUE THREAD

**Issue by mgroeneweg** [mendix/generator-mendix#33]
Excluding the theme leads to funny errors and and empty style when cloning the project from GitHub.

**Comment by mgroeneweg** [comment]
Any news here? Still happens...

**Comment by JelteMX** [comment]
I updated the `gitignore`, removed the theme folder. Should be fixed in version 2.2.4, published on NPM

**Comment by mgroeneweg** [comment]
Thanks! Looking at the commit, I can't imagine how I could have missed that one when searching how it built the widget structure on my laptop. <shame>
